### PR TITLE
Support for Ext Designer

### PR DESCRIPTION
**Pull request by oyvindkinsey**
Added support for Ext Designer by supporting the format=json query parameter.

### CODE REVIEW

**Comment by gimmi** [comment]
Hi,
thanks for the pull request.

The only information for Ext Designer support in Ext Direct that i found is in this video, at around 12:50

http://docs.sencha.com/ext-js/4-0/#!/video/17876920

however, it doesn't mention about the new property "descriptor" that you added to the generated JSON. What's this about? Have you some other documentation about designer integration?

Thanks

**Comment by oyvindkinsey** [comment]
I know, there's really not much information about it anywhere..

I found some blog post about it, where the 'descriptor' was added, tested it and found it to work.
From a forum post a Sencha member said that the 'descriptor`is really just the`Ext.app.REMOTE_API = ....` moved into the JSON - I have no idea what it is used for since this string is not used in anyway when loading the api the regular way...

But this does work and seems to be according to the information I found.. Of course, how to now use this in the Designer is the next problem as the documentation is pretty poor..

**Comment by gimmi** [comment]
Ok, i see you have used "ext.app" rather than "Ext.app" (with capital E). Is this intentional or not?

Have you some link to blog/forum you mentioned? I wish to add it as comment for documentation.

**Comment by oyvindkinsey** [comment]
Ah, thats a typo :)

http://davehiren.blogspot.com/2011/03/configure-extdirect-api-with-ext.html
http://www.sencha.com/forum/showthread.php?102357-Extremely-Easy-Ext.Direct-integration-with-PHP#post_message_480214

**Comment by gimmi** [comment]
Ok, thanks. I will integrate your pull request asap, but before i want to change the way namespace is specified (now is specified from querystring and this require specifying it both in designer and in app code).

**Pull request closed without merging**
